"""Assemble stage service — validate and package the generated plugin tree.

Pure Python, no LLM. Writes plugin.json, README, .gitignore, runs the
three validators (links, template leaks, frontmatter), grades the run,
and optionally zips the tree.

The service collects everything into a structured ``AssembleResult``
so the CLI can render the existing multi-line report from the return
value. Emits minimal events (stage_start/finish) for consumers like
``run_pipeline`` that aggregate across stages.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict

from franklin.assembler import (
    BrokenLink,
    FrontmatterIssue,
    TemplateLeak,
    find_template_leaks,
    generate_readme,
    package_plugin,
    validate_frontmatter,
    validate_links,
    write_plugin_manifest,
)
from franklin.checkpoint import RunDirectory
from franklin.grading import RunGrade, grade_run, write_metrics
from franklin.services.events import ProgressCallback, StageFinish, StageStart
from franklin.services.reduce import NoPlanError

_STAGE = "assemble"

_GITIGNORE_CONTENTS = (
    "# Generated by franklin assemble\n__pycache__/\n*.pyc\n.DS_Store\n*.swp\n.env\n"
)


class PluginNotBuiltError(RuntimeError):
    """The plugin output directory doesn't exist — reduce hasn't run."""

    def __init__(self, plugin_root: Path) -> None:
        self.plugin_root = plugin_root
        super().__init__(f"no generated plugin at {plugin_root} — run `franklin reduce` first")


class _Base(BaseModel):
    model_config = ConfigDict(extra="forbid")


class AssembleInput(_Base):
    run_dir: Path
    zip_archive: bool = False


class AssembleResult(_Base):
    model_config = ConfigDict(extra="forbid", arbitrary_types_allowed=True)

    run_dir: Path
    plugin_root: Path
    manifest_path: Path
    readme_path: Path
    gitignore_written: bool
    total_files: int
    markdown_files: int
    broken_links: list[BrokenLink]
    template_leaks: list[TemplateLeak]
    frontmatter_issues: list[FrontmatterIssue]
    grade: RunGrade
    metrics_path: Path
    archive_path: Path | None = None

    @property
    def issue_count(self) -> int:
        return len(self.broken_links) + len(self.template_leaks) + len(self.frontmatter_issues)


class AssembleService:
    def run(
        self,
        params: AssembleInput,
        *,
        progress: ProgressCallback | None = None,
    ) -> AssembleResult:
        emit = progress or (lambda _event: None)

        run = RunDirectory(params.run_dir)
        if not run.plan_json.exists():
            raise NoPlanError(f"no plan.json in {params.run_dir} — run `franklin plan` first")

        plan = run.load_plan()
        plugin_root = run.output_dir / plan.plugin.name
        if not plugin_root.exists():
            raise PluginNotBuiltError(plugin_root)

        emit(StageStart(stage=_STAGE))

        manifest_path = write_plugin_manifest(plugin_root, plan.plugin)
        book = run.load_book()
        readme_path = generate_readme(plugin_root, plan=plan, book=book)

        gitignore_path = plugin_root / ".gitignore"
        gitignore_written = False
        if not gitignore_path.exists():
            gitignore_path.write_text(_GITIGNORE_CONTENTS)
            gitignore_written = True

        files = sorted(p for p in plugin_root.rglob("*") if p.is_file())
        markdown_files = [p for p in files if p.suffix == ".md"]

        broken_links = validate_links(plugin_root)
        template_leaks = find_template_leaks(plugin_root)
        frontmatter_issues = validate_frontmatter(plugin_root)

        grade = grade_run(params.run_dir)
        metrics_path = write_metrics(params.run_dir, grade)

        archive_path: Path | None = None
        if params.zip_archive:
            archive_path = run.output_dir / f"{plan.plugin.name}.zip"
            package_plugin(plugin_root, archive_path)

        issue_count = len(broken_links) + len(template_leaks) + len(frontmatter_issues)
        emit(
            StageFinish(
                stage=_STAGE,
                summary=f"grade {grade.letter} · {issue_count} issue(s)",
            )
        )

        return AssembleResult(
            run_dir=run.root,
            plugin_root=plugin_root,
            manifest_path=manifest_path,
            readme_path=readme_path,
            gitignore_written=gitignore_written,
            total_files=len(files),
            markdown_files=len(markdown_files),
            broken_links=broken_links,
            template_leaks=template_leaks,
            frontmatter_issues=frontmatter_issues,
            grade=grade,
            metrics_path=metrics_path,
            archive_path=archive_path,
        )


__all__ = [
    "AssembleInput",
    "AssembleResult",
    "AssembleService",
    "PluginNotBuiltError",
]
