"""Generate a README.md for the assembled plugin.

Produces a GitHub-ready README from the plan metadata and output tree,
matching the style of published Claude Code plugin repos like
palkan/skills and mcrundo/sustainable-rails-skill. No LLM calls — this
is deterministic assembly from the plan + book metadata.
"""

from __future__ import annotations

from pathlib import Path

from franklin.schema import ArtifactType, BookManifest, PlanManifest


def _first_sentence(text: str) -> str:
    """Extract the first sentence from a brief, for table display."""
    # Split on ". " or ":" to get just the opening clause.
    for sep in (". ", ": "):
        if sep in text:
            return text[: text.index(sep) + 1].rstrip()
    # No period — return as-is but cap length.
    if len(text) > 120:
        return text[:117] + "..."
    return text


def generate_readme(
    plugin_root: Path,
    *,
    plan: PlanManifest,
    book: BookManifest,
    repo: str | None = None,
) -> Path:
    """Write a README.md to ``plugin_root`` and return the path."""
    plugin = plan.plugin
    authors = ", ".join(book.metadata.authors) or "Unknown"

    lines: list[str] = []

    # ---- header -----------------------------------------------------------

    lines.append(f"# {plugin.name}")
    lines.append("")
    lines.append(
        f"A [Claude Code](https://docs.anthropic.com/en/docs/claude-code) plugin "
        f"based on *{book.metadata.title}* by {authors}."
    )
    lines.append("")

    if plugin.description:
        lines.append(plugin.description)
        lines.append("")

    # ---- install ----------------------------------------------------------

    lines.append("## Install")
    lines.append("")
    if repo:
        lines.append("```bash")
        lines.append(f"claude plugin marketplace add {repo}")
        lines.append(f"claude plugin install {plugin.name}@{plugin.name}")
        lines.append("```")
    else:
        lines.append("```bash")
        lines.append("claude plugin marketplace add owner/repo")
        lines.append(f"claude plugin install {plugin.name}@{plugin.name}")
        lines.append("```")
        lines.append("")
        lines.append(
            "*Replace `owner/repo` with the GitHub repository "
            "after publishing with `franklin push`.*"
        )
    lines.append("")

    # ---- commands ---------------------------------------------------------

    commands = [a for a in plan.artifacts if a.type == ArtifactType.COMMAND]
    if commands:
        lines.append("## Commands")
        lines.append("")
        lines.append("| Command | Purpose |")
        lines.append("|---------|---------|")
        for cmd in commands:
            cmd_name = Path(cmd.path).stem
            lines.append(f"| `/{plugin.name}:{cmd_name}` | {_first_sentence(cmd.brief)} |")
        lines.append("")

    # ---- agents -----------------------------------------------------------

    agents = [a for a in plan.artifacts if a.type == ArtifactType.AGENT]
    if agents:
        lines.append("## Agents")
        lines.append("")
        for agent in agents:
            agent_name = Path(agent.path).stem
            lines.append(f"- **{agent_name}** — {_first_sentence(agent.brief)}")
        lines.append("")

    # ---- reference files --------------------------------------------------

    references = [a for a in plan.artifacts if a.type == ArtifactType.REFERENCE]
    if references:
        lines.append("## Reference Files")
        lines.append("")
        lines.append(f"{len(references)} reference files organized into:")
        lines.append("")

        # Group by directory under references/
        groups: dict[str, list[str]] = {}
        for ref in references:
            parts = Path(ref.path).parts
            # Find the 'references' segment and take the next part as group
            try:
                ref_idx = list(parts).index("references")
                group = parts[ref_idx + 1] if ref_idx + 1 < len(parts) - 1 else "general"
            except ValueError:
                group = "general"
            groups.setdefault(group, []).append(Path(ref.path).stem)

        for group, files in sorted(groups.items()):
            file_list = ", ".join(sorted(files))
            lines.append(f"- `references/{group}/` — {file_list}")
        lines.append("")

    # ---- generated by -----------------------------------------------------

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by [Franklin](https://github.com/mcrundo/franklin) "
        f"from *{book.metadata.title}*."
    )
    lines.append("")

    readme_path = plugin_root / "README.md"
    readme_path.write_text("\n".join(lines))
    return readme_path
